name: Docs creationg 

on: 
  push:
    branches:
  pull_request: 
    branches: [gh-pages]
    types: [opened, synchronize, closed]

jobs:
  docs:
  # deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          pip install sphinx myst-parser
          pip install sphinxawesome-theme --pre

      - name: Sphinx build
        run: |
          sphinx-build . docs_new_theme

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}

      - name: Deploy Docs 2
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/heads/gh-pages' }}

        with:
          publish_branch: new_docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs_new_theme/
          force_orphan: true